# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PiOnFyreLight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  
  # Pods for PiOnFyreLight

  target 'PiOnFyreLightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PiOnFyreLightUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
